#!/bin/sh

case $1 in
	"b" | "build")
    WGPU_POWER_PREF='high' \
    WGPU_BACKEND='webgpu' \
    RUSTFLAGS='--cfg=web_sys_unstable_apis -C target-feature=+atomics,+bulk-memory,+mutable-globals' \
		cargo build --no-default-features --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort
    wasm-bindgen --out-dir ./pkg --target no-modules \
    $CARGO_TARGET_DIR/wasm32-unknown-unknown/release/moksha_wgpu.wasm \
	;;
	"s" | "serve")
		python3 server.py
	;;
	"w" | "watch")
		cargo watch -w src -w Cargo.toml -s "$0 build"
	;;
	"d" | "document")
		D_PRIVATE="--document-private-items"
		D_OPEN="--open"
		SECOND="$2"
		VALID=true
		while [ "$2" != "" ]; do
			if [[ ${SECOND:1:1} == "-" ]]; then
				case $2 in
				"--public")
					D_PRIVATE=""
					;;
				"--quiet")
					D_OPEN=""
					;;
				*)
					VALID=false
					;;
				esac
			elif [ ${SECOND:0:1} == "-" ]; then
				for i in $(seq -s " " 1 ${#SECOND}); do
					case ${SECOND:i:1} in
					"p")
						D_PRIVATE=""
						;;
					"q")
						D_OPEN=""
						;;
					"")
						break
						;;
					*)
						VALID=false
						;;
					esac
				done
			else
				VALID=false
				break
			fi
			shift
		done
		if [ "$VALID" = true ]; then
			echo "cargo doc $D_PRIVATE $D_OPEN --workspace"
			cargo doc $D_PRIVATE $D_OPEN --workspace
		else
			echo "build document [-|--] [(p)ublic | (q)uiet]"
		fi
	;;
	*)
		echo "build [(b)uild | (s)erve | (r)un | (w)atch | (d)ocument]"
esac
