#!/bin/sh

case $1 in
	"b" | "build")
		cargo build --release
    wasm-bindgen --out-dir ./pkg --target no-modules \
    $CARGO_TARGET_DIR/wasm32-unknown-unknown/release/wgpu_test.wasm
    curl http://localhost:8080/mark-stale
	;;
	"s" | "serve")
		python3 server.py
	;;
	"d" | "document")
    cargo doc --document-private-items --open
	;;
	"w" | "watch")
		cargo watch -w src -w Cargo.toml -s "$0 build"
	;;
	*)
		echo "build [(b)uild | (s)erve | (d)ocument | (w)atch]"
esac
