[package]
name = "wgpu-test"
version = "0.1.0"
authors = ["nrayamajhee <nishan@rayamajhee.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.web-sys]
version = "0.3.53"
features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "HtmlStyleElement",
  "HtmlHeadElement",
  "HtmlImageElement",
  "Navigator",
  "DedicatedWorkerGlobalScope",
  "CssRule",
  "ErrorEvent",
  "Location",
  "CssStyleDeclaration",
  "Performance",
  "HtmlStyleElement",
  "KeyboardEvent",
  "NodeList",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Window",
  "DomStringMap",
  "Crypto",
]

[dependencies]
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.18"
js-sys = "0.3.45"
console_error_panic_hook = { version = "0.1.6" }
wee_alloc = { version = "0.4.5" }
rayon = "1.5.0"
console_log = { version = "0.2", features = ["color"] }
wgpu = { version = "0.12", default-features = false }
log = "0.4.16"
bytemuck = { version = "1.9.1", features = [ "derive" ] }
image = "0.24.2"
genmesh = "0.6.2"
strum = { version = "0.24.0", features = ["derive"] }
nalgebra = "0.31.0"
maud = "0.23.0"



[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"


