[package]
name = "wgpu-test"
version = "0.1.0"
authors = ["nrayamajhee <nishan@rayamajhee.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.web-sys]
version = "0.3.59"
features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "HtmlStyleElement",
  "HtmlHeadElement",
  "HtmlImageElement",
  "Navigator",
  "DedicatedWorkerGlobalScope",
  "CssRule",
  "ErrorEvent",
  "Location",
  "CssStyleDeclaration",
  "Performance",
  "HtmlStyleElement",
  "KeyboardEvent",
  "MouseEvent",
  "WheelEvent",
  "NodeList",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Window",
  "DomStringMap",
  "Crypto",
  "GpuDevice",
  "GpuAdapter",
  "GpuCanvasConfiguration",
  "GpuCanvasAlphaMode",
  "GpuTextureFormat"
]

[dependencies]
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59"
console_error_panic_hook = "0.1.7"
wee_alloc = "0.4.5"
rayon = "1.5.3"
console_log = { version = "0.2.0", features = ["color"] }
wgpu = { git = "https://github.com/nrayamajhee/wgpu.git", branch="main", default-features = false }
log = "0.4.17"
bytemuck = { version = "1.12.1", features = [ "derive" ] }
image = "0.24.3"
genmesh = "0.6.2"
strum = { version = "0.24.1", features = ["derive"] }
nalgebra = "0.31.1"
maud = "0.23.0"
futures-channel = "0.3.23"



[dev-dependencies]
wasm-bindgen-test = "0.3.32"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
