[package]
name = "wgpu-test"
version = "0.1.0"
authors = ["nrayamajhee <nishan@rayamajhee.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.web-sys]
version = "0.3.58"
features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "HtmlStyleElement",
  "HtmlHeadElement",
  "HtmlImageElement",
  "Navigator",
  "DedicatedWorkerGlobalScope",
  "CssRule",
  "ErrorEvent",
  "Location",
  "CssStyleDeclaration",
  "Performance",
  "HtmlStyleElement",
  "KeyboardEvent",
  "MouseEvent",
  "WheelEvent",
  "NodeList",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Window",
  "DomStringMap",
  "Crypto",
]

[dependencies]
wasm-bindgen = "0.2.81"
wasm-bindgen-futures = "0.4.31"
js-sys = "0.3.58"
console_error_panic_hook = "0.1.7"
wee_alloc = "0.4.5"
rayon = "1.5.3"
console_log = { version = "0.2.0", features = ["color"] }
wgpu = { version = "0.13.1", default-features = false }
log = "0.4.17"
bytemuck = { version = "1.10.0", features = [ "derive" ] }
image = "0.24.2"
genmesh = "0.6.2"
strum = { version = "0.24.1", features = ["derive"] }
nalgebra = "0.31.0"
maud = "0.23.0"



[dev-dependencies]
wasm-bindgen-test = "0.3.31"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
